### ISSUE TITLE
Add more GPU providers

### ISSUE THREAD

**Issue by julien-blanchon** [alexandrevilain/devpod-provider-ovhcloud#23]
![Screenshot from 2023-10-13 16-45-37](https://github.com/alexandrevilain/devpod-provider-ovhcloud/assets/11278197/d37734ef-3130-4e29-b768-3b2d9a2d2528)
Some flavor are not available such as t1-le-45 or a100

**Comment by julien-blanchon** [comment]
I'm closing this as it get merged

**Comment by alexandrevilain** [comment]
This is now released as part of https://github.com/alexandrevilain/devpod-provider-ovhcloud/releases/tag/v0.0.5

**Comment by julien-blanchon** [comment]
Great :tada:
